language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:~1.0"
  - composer install

before_script:
  - chmod -R a+w runtime
  - mysql -e 'create database bootstrap_yii2_tests;'
  - php yii create-local-config/init
  - composer test-prepare
  - composer test-build

script:
  - composer test
